### ISSUE TITLE
mario wont get out of C-up mode when freezeing camera

### ISSUE THREAD

**Issue by Supergub5871** [Llennpie/Saturn#16]
it wont go out of C-up mode pressing b does nothing

https://user-images.githubusercontent.com/90076568/177218546-111bdd1b-a5ba-48a5-915d-753c5bb53990.mp4

**Comment by Agent-11** [comment]
That might be intentional, unfreeze the camera to get out of C-up mode?

**Comment by Supergub5871** [comment]
not usefull then how will i freeze the camera in C-up mode thats how everyone does it

**Comment by Supergub5871** [comment]
nvm

**Comment by Agent-11** [comment]
![what](https://user-images.githubusercontent.com/44549182/177218941-43cdd636-1038-46ac-9890-9619d3cddf09.png)

**Comment by Supergub5871** [comment]
what

**Comment by integerbang** [comment]
> not usefull then how will i freeze the camera in C-up mode thats how everyone does it

Toggling Machinima Camera replaces the camera mode you were previously using. How you're supposed to move the camera is done within this mode (i.e., pressing Shift then moving the mouse while holding down on the view) instead of how one would do it in any other tool.

From what I can tell, the button used to toggle Machinima Camera is also mapped to toggling C-Up Mode (probably by default?), so that may be where the confusion comes from (assuming you're using a controller). Also, I feel Mario should exit out of C-Up Mode automatically if the player turns on Machinima Camera, but I guess that's up to @Llennpie to decide.

**Comment by Llennpie** [comment]
First person mode should work the same regardless of whether the machinima camera is enabled or not. Pressing C-Up enters first person and pressing C-Down exits it.

**Comment by integerbang** [comment]
> First person mode should work the same regardless of whether the machinima camera is enabled or not. Pressing C-Up enters first person and pressing C-Down exits it.

That doesn't happen if Machinima Camera is already enabled going by the video.

**Comment by Llennpie** [comment]
> That doesn't happen if Machinima Camera is already enabled going by the video.

The video shows B being pressed, not C-Down.

**Comment by integerbang** [comment]
> The video shows B being pressed, not C-Down.

Why would that matter? You can exit C-Up Mode by pressing B.

**Comment by Supergub5871** [comment]
stop commenting i fixed it by changine the controls

**Comment by Supergub5871** [comment]
just delete this

**Comment by integerbang** [comment]
> just delete this

I was planning on opening a different issue, either way.
