### ISSUE TITLE
Executable didn't install

### ISSUE THREAD

**Issue by PaperVb64** [Llennpie/Saturn#2]
When i go into the folder, there's no executable. 

How it happened:
1. Go to Terminal
2. Install as usual
3. Go to build > us_pc
4. No executable or file at least saying "sm64saturn" or something.

**Expected behavior**

A .us file or at least something would show up
![Screenshot 2021-11-25 2 15 24 PM](https://user-images.githubusercontent.com/94991205/143491963-054da66b-81ba-4385-9eb7-0ab750ed3677.png)

**Desktop:**
 - OS: Chrome OS (installed Saturn via Terminal)
 - Browser Google Chrome
 - Version 94.0.4606.124 (Official Build) (64-bit)
 

**Smartphone:**
 - Device: Samsung S7 (didn't use this, but it's important apparently)
 - OS: Android
 - Browser: Samsung Internet (Preferred) 
 - Version Don't know. Possibly 8.0 Oreo.

**Comment by Llennpie** [comment]
I've never tried compiling Saturn from Chrome OS, so I'm not sure if it'd even work at all. If the executable doesn't appear, it means there was an error. Does it say anything in the terminal? Send a screenshot if you can

**Comment by PaperVb64** [comment]
> I've never tried compiling Saturn from Chrome OS, so I'm not sure if it'd even work at all. If the executable doesn't appear, it means there was an error. Does it say anything in the terminal? Send a screenshot if you can

Uhhh yeah. i closed the Terminal before i could screenshot, but there was an error towards the end. I'ma try again and see if it happens. Also, i've got the actual base port of sm64 running, so i was kinda confused.

**Comment by PaperVb64** [comment]
K, so i got an error the second time around. What does this mean?
![Screenshot 2021-11-25 5 04 05 PM](https://user-images.githubusercontent.com/94991205/143503521-46a33c5b-3694-427e-a89c-b9de3f7bc59a.png)

**Comment by Llennpie** [comment]
Looks like a linker error with C++. Can you run `gcc --version` for me? This error tends to happen on GCC versions under 9, you may need to update it.

**Comment by PaperVb64** [comment]
yay. an issue with the Terminal. I'll try updating and re-installing. i'll get back to you when i'm done.

**Comment by PaperVb64** [comment]
So, i only saw this: (Debian 8.3.0-6) 8.3.0. Is that outdated?

**Comment by PaperVb64** [comment]
o. it says 8. So how do i update

**Comment by Llennpie** [comment]
Yeah, 8 is outdated. You need at least 9 to compile Saturn. Try something along the lines of:
```
sudo apt install gcc-9

**Comment by PaperVb64** [comment]
Installing GCC 9 doesn't work :(

**Comment by PaperVb64** [comment]
all it says is that it's unable to locate the package. Should i get the package of the Ubuntu Website and run it off local?

**Comment by Llennpie** [comment]
Hmm, maybe try this PPA.
```
sudo add-apt-repository ppa:jonathonf/gcc
sudo apt-get update
sudo apt-get install gcc-9
```

Then relaunch your terminal and run `gcc --version` to see if it updated.

> all it says is that it's unable to locate the package. Should i get the package of the Ubuntu Website and run it off local?

If the above doesn't work, yeah, feel free.

**Comment by PaperVb64** [comment]
first command sudo add-apt-repository ppa:jonathonf/gcc doesn't work.

**Comment by PaperVb64** [comment]
is there a speciffic version i should get?

**Comment by integerbang** [comment]
> So, i only saw this: (Debian 8.3.0-6) 8.3.0. Is that outdated?

I'm assuming you are using Debian 10 (I don't know for sure considering you mentioned Chrome OS) since that seems to be the latest available version of `gcc` for that release. Later versions seem to be available for Debian 11, however, which would typically require a [system upgrade](https://www.debian.org/releases/stable/amd64/release-notes/ch-upgrading.en.html) at that point.

Alternatively, you could just add the repository yourself, but I don't know if this is recommended since I don't use Debian as my main operating system.

If you aren't sure how to do that, here's how to do so just in case.

1. Run `sudo apt edit-sources` from a terminal session.
2. If you're prompted with a list of editors to select for this session onwards, choose which one you're most comfortable with. If you aren't entirely sure, you may choose the one described by the list as the easiest (in my case, that'd be `/bin/nano`).
3. It should open `/etc/apt/sources.list` using the editor you selected (or configured if it had already been set beforehand). Once it is open, add a new line, then append `deb http://deb.debian.org/debian bullseye main` to the end of the file.
4. Save the file, then close it. (In `/bin/nano`, you can just press `Ctrl + X` to exit, and it'll prompt if you want to save.)

Hope this helps!

**Comment by PaperVb64** [comment]
This looks too hard, and i didn't know what to do after the first command. Even though it may seem like i'm good at this stuff, i'm actually not too keen with tech. I AM a tech fanatic however, so i'll get around to learning how to use the terminal in full. In the mean time, could you show me an easier option? If not, thanks for trying to help at least.

**Comment by Llennpie** [comment]
To make things short and simple, the latest version of GCC on your version of Debian (Linux) is 8. Saturn needs a version of at least 9.

You should try updating Debian to the latest version. I believe Debian Bullseye released on Chrome OS earlier this year (might still be on the dev channel) and it has support for newer versions of GCC. I’m not sure about the specifics of updating Debian on Chrome OS, but a quick Google search should do the trick.

**Comment by PaperVb64** [comment]
Errr... Did i forget to mention, i'm using my school account? I used a shortcut to get the Terminal. Is there a way to change settings in-terminal?

**Comment by Llennpie** [comment]
I hate to be that person, but trying to do all this through a school-issued chromebook could probably get in you in serious trouble. I’ll close this for now, since we’ve figured out the main issue. You’ll have to look around a bit on Google if you want to update Debian, but I don’t have Chrome OS myself so I can’t give any tips or advice.

**Comment by PaperVb64** [comment]
k.

**Comment by PaperVb64** [comment]
Oh by the way, are there any other machinima editors with the same features as Saturn? Just asking so i can have something to do while waiting for my windows PC to be found :)

**Comment by integerbang** [comment]
> Oh by the way, are there any other machinima editors with the same features as Saturn? Just asking so i can have something to do while waiting for my windows PC to be found :)

There's a [new release of Saturn](https://github.com/Llennpie/Saturn/releases/tag/sme-alpha1) that doesn't require compilation.

**Comment by PaperVb64** [comment]
Oh! thanks a lot!

**Comment by PaperVb64** [comment]
Oh and also, just a late comment to Llennpie, i put linux on here a few months ago.

**Comment by PaperVb64** [comment]
PS: i figured out the add-apt-repository error. Turns out, you need to install a separate package named "software-priorities-common".

**Comment by PaperVb64** [comment]
o also it's technically my computer i'm using. i just signed into my school account.
