### ISSUE TITLE
Compiling won't work using sm64pcbuilder2 on Windows

### ISSUE THREAD

**Issue by MasterNama17083** [Llennpie/Saturn#23]
Hello! I'm trying to build using sm64pcbuilder2 because I did put an original sm64 us rom at `Saturn-legacy\baserom.us.z64`
and trying to build again now it says error message:
_(probably python3 feels very outdated or missing original python **_not python3_** ver or `extract_assets.py` won't respond to extract rom, idk.)_
![image](https://user-images.githubusercontent.com/80534869/225919353-b49379ac-9f56-4c91-848a-864d915c97ce.png)

**Comment by integerbang** [comment]
In addition, I'd recommend going to [PC Port Central](https://discord.gg/7k9AzWjhzw) for assistance regarding sm64pcBuilder2 first instead of creating issues here.

sm64pcBuilder2 refers you to PC Port Central whenever it reports a build failure, as the people who've worked on it manage the server. This issue tracker isn't the place to report problems using sm64pcBuilder2 or similar tools not made by anyone that works on Saturn otherwise.

**Comment by MasterNama17083** [comment]
> Refer to the "[Updating MSYS2](https://www.msys2.org/docs/updating/)" page from the official MSYS2 website for instructions if you couldn't get rid of the issue alone using sm64pcBuilder2.

![image](https://user-images.githubusercontent.com/80534869/226119135-02db458b-1b7b-489c-966a-7ed8fd08bd42.png)
Yep, it's already up to date but saw.

**Comment by MasterNama17083** [comment]
brb, issue start soon
