### ISSUE TITLE
Graphical Error When Using Third-Point Filter

### ISSUE THREAD

**Issue by KrazyGyro9704** [Llennpie/Saturn#26]
**Describe the bug**
When using the Third-Point texture filter in Saturn, the build can produce a result that isn't accurate to its intended performance. Textures will have many small gaps in them and certain sky box tiles can flicker, sometimes even changing to another texture from the level.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Settings'
3. Scroll down to 'Texture Filtering'
4. Click on 'Third-Point'
5. Restart the program.
6. See error.

**Expected behavior**
Third-Point should not be causing these graphical errors. Instead, it's intended to apply a somewhat "diagonal motion blur" effect to all in-game textures.

**Screenshots**
![image](https://user-images.githubusercontent.com/106826670/232332593-a93cc3db-afea-4e95-a16f-2e623f6c5c22.png)

**Desktop:**
 - OS: Windows 10
 - Firefox
 - 112.0

**Additional context**
The glitch could be involved with changing in-game textures via file editing in the repository. I have not experienced this glitch before I started doing so.

**Comment by Llennpie** [comment]
The three-point filter is left over from [sm64ex](https://github.com/sm64pc/sm64ex)'s development. I haven't modified it in any way since initially forking Saturn. The filter isn't perfect but as far as I'm aware it's identical to the actual three-point filter on N64 hardware and the GLideN64 plugin. Those artifacts are probably intended.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/44985633/232376348-aa9f9d5f-8aa9-4ebd-9e3f-788fc0559bdd.png">

As for the skybox issue, it should have been fixed in #24. Are you on the latest commit?

**Comment by integerbang** [comment]
> As for the skybox issue, it should have been fixed in #24. Are you on the latest commit?

That pull request fixes the bug that prevents the background in the Secret Aquarium from being replaced properly. The problem they're describing doesn't seem to be related to that.
