### ISSUE TITLE
Linux Refuses to boot Saturn Moon

### ISSUE THREAD

**Issue by PaperVb64** [Llennpie/Saturn#7]
**Describe the bug**
Soooo, i had to uninstall and reinstall Linux, and so saturn went along with it. But when i tried to reinstall it, it threw me an error.

**To Reproduce**
i don't exactly know how to reproduce it. it just happened

**Expected behavior**
the exicutable to actually run.

**Screenshots**
![image](https://user-images.githubusercontent.com/94991205/149844981-b05dcb88-a42d-4eb9-a6d3-81aa23487f53.png)

**Desktop (please complete the following information):**
 - OS: Google Chrome OS Version 99.0.4807.0 (Official Build) dev (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android Oreo (8.0)
 - Browser: Google Chrome
 - Version: Latest

**Comment by Llennpie** [comment]
Try installing these dependencies.
```
sudo apt install build-essential git python3 libglew-dev libsdl2-dev curl
```

**Comment by integerbang** [comment]
@PaperVb64, can you please run `lsb_release -a` and share the resulting output here? You didn't specify what operating system you're using on your Linux container right now, and since Saturn isn't running on Chrome OS natively, the included specification doesn't help much.

Regardless, based on what you've stated in your description of this issue, you've mentioned that you had to set up Linux on Chrome OS again recently. Going by that statement, I'd recommend installing the dependencies for Saturn, as @Llennpie has already suggested. You can check out build dependencies for other Linux distributions [here](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Linux#install-build-dependencies).

Feel free to reply if our suggestion doesn't work.

**Comment by PaperVb64** [comment]
I know which version i'm using. It's Debian Bullseye, not native Chrome OS.

**Comment by Llennpie** [comment]
I'm going to close the issue as it seems to have been resolved. If that's not the case let me know and I'll reopen it.
*(On a side note, I recommend you join the Discord for small bugs like this since we can help faster and have better contact)*
